#!/usr/bin/env bash
# Install and configure nginx on the server
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
