#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
sudo sed -i "/# SSL configuration/ i\ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-enabled/default
sudo service nginx restart
