#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i -e '/listen 80 default_server;/a\' -e '\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' file
sudo service nginx restart
