#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another 
# page and to have a custom 404 page.

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
sudo sed -i "/# SSL configuration/ i\ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "/# SSL configuration/ i\ \terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html \{\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n" /etc/nginx/sites-enabled/default
sudo service nginx restart
