#!/usr/bin/env bash
# Configures nginx to have a custom header

HOSTNAME=$(hostname)

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
sudo sed -i "/^.*sendfile.*/i add_header X-Served-By ${HOSTNAME};" /etc/nginx/nginx.conf
sudo service nginx restart
