#!/usr/bin/env bash
# Set ups HAproxy

sudo apt-get update
sudo apt-get -y install haproxy
sudo cat >> /etc/haproxy/haproxy.cfg << EOF
frontend 1662-lb-01
        bind *:80
        mode http
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 1662-web-01 35.190.181.185:80 check
        server 1662-web-02 35.185.113.213:80 check
EOF
sudo /etc/init.d/haproxy restart
