#!/usr/bin/env bash
# Loops from 1 to 10 and:
# * Displays bad luck for the 4th loop iteration
# * Displays good luck for the 8th loop iteration
# * Displays Holberton School for the other iterations

i="0"
while [ $i -lt 10 ]; do
    if ((i == 3))
    then
        echo "bad luck"
    elif ((i == 7))
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    i=$((i+1))
done
