#!/usr/bin/env bash
# Configures ufw so that it blocks all incoming traffic, except the following
# TCP ports: 22 (SSH), 80 (HTTP), 443 (HTTPS SSL)

sudo ufw deny incoming
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
