#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

echo -e "127.0.0.2\tlocalhost" > ~/host.new
echo -e "8.8.8.8\t\tfacebook.com" >> ~/host.new
cp -f ~/hosts.new /etc/hosts
