#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

NEW=~/host.new
OLD=/etc/hosts

echo -e "127.0.0.2\tlocalhost" > "$NEW"
echo -e "8.8.8.8\t\tfacebook.com" >> "$NEW"
cp -f "$NEW" "$OLD"
